# Generated by Django 3.2.12 on 2022-02-12 10:14

from django.db import migrations, models
import django.db.models.deletion
import server.utils.db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.db.random_slug, max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('media', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.db.random_slug, max_length=40, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('media', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.db.random_slug, max_length=40, unique=True)),
                ('question_title', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=1500)),
                ('solution_answer', models.CharField(max_length=50)),
                ('solution_text', models.CharField(max_length=1500)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=50)),
                ('question_medias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='questions.questionmedia')),
                ('solution_medias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.solutionmedia')),
            ],
        ),
    ]
