# Generated by Django 3.2.12 on 2022-02-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_medias',
        ),
        migrations.AddField(
            model_name='question',
            name='question_medias',
            field=models.ManyToManyField(blank=True, null=True, to='questions.QuestionMedia'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution_medias',
        ),
        migrations.AddField(
            model_name='question',
            name='solution_medias',
            field=models.ManyToManyField(blank=True, null=True, to='questions.SolutionMedia'),
        ),
    ]
