# Generated by Django 3.2.12 on 2022-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20220212_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_medias',
            field=models.ManyToManyField(blank=True, to='questions.QuestionMedia'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution_medias',
            field=models.ManyToManyField(blank=True, to='questions.SolutionMedia'),
        ),
    ]
